### ISSUE TITLE
new NativeEventEmitter()` requires a non-null argument

### ISSUE THREAD

**Issue by Goye** [skedlife/react-native-boundary#1] opened 2024-02-07 18:56 UTC
Hey, @skedlife!

I am seeing the following error when I tried to run the library with an updated react-native version (0.73.3):

<img src="https://github.com/eddieowens/react-native-boundary/assets/11186639/3b7c625d-b4cd-44d7-a7e8-8e9fdd530cc2" height="480" />

Digging deeper, I realized that the `const {RNBoundary} = NativeModules;` returns nothing.

``` index.js
const {RNBoundary} = NativeModules;

const TAG = "RNBoundary";

const boundaryEventEmitter = new NativeEventEmitter(RNBoundary);
```

I've also tried adding the methods **startObserving/stopObserving** recommended by the [documentation](https://reactnative.dev/docs/native-modules-ios) without success.

Do you have any idea what I can do to fix it?

Thank you so much!

# Platform
iOs

# Environment

package | version
-- | --
react-native | 0.73.3
react-native-boundary-sked | 1.1.4
node | 18.16.1
npm or yarn | npm v9.5.1

**Comment by NuclearKev** [comment] 2024-02-07 20:27
Hi @Goye, we haven't updated to 0.73.x yet and am only on 0.72.6. We have some plans to update soon and I am able to reproduce this issue.

**Comment by Goye** [comment] 2024-02-07 20:52
Perfect @NuclearKev, Thank you very much for your quick response!

**Comment by NuclearKev** [comment] 2024-02-07 21:45
@Goye I've done a very quick and dirty update to 0.73.4 for iOS only and I'm not having that error. How are you using the library? Can you give me more information?

**Comment by Goye** [comment] 2024-02-08 15:23
Oh really 🤔, I am just calling:
```
import Boundary, { Events } from 'react-native-boundary-sked';
```

And adding its respective locations and emitters 
```
Boundary.add(boundary).catch((error) =>
...
Boundary.on(Events.ENTER, (id) => {
Boundary.on(Events.EXIT, (id) => {
```

But I had to patch the package due to some SDK updates, let me try removing the patch @NuclearKev

**Comment by NuclearKev** [comment] 2024-02-08 15:48
> ```
> import Boundary, { Events } from 'react-native-boundary-sked';
> ```
> 
> And adding its respective locations and emitters 
> 
> ```
> Boundary.add(boundary).catch((error) =>
> ...
> Boundary.on(Events.ENTER, (id) => {
> Boundary.on(Events.EXIT, (id) => {
> ```

Hmm, that looks correct. Let me know if the patch removal fixes it.

**Comment by Goye** [comment] 2024-02-08 17:32
Hey! @NuclearKev 

I've created a project from scratch using the latest version of react native and I am seeing the same problem.
<img src="https://github.com/skedlife/react-native-boundary/assets/11186639/98e95fd7-ec62-4436-a038-9e350b50f4ec" height="480" />


These are my dependencies

```
 "react": "18.2.0",
 "react-native": "0.73.4",
"react-native-boundary-sked": "^1.1.4"
```

Moreover, I've added the required permissions `NSLocationAlwaysAndWhenInUseUsageDescription, NSLocationAlwaysUsageDescription, NSLocationWhenInUseUsageDescription` to the Info.plist

And this is how my implementation looks like
```
import Boundary, {Events} from 'react-native-boundary-sked';
...
useEffect(() => {
    Boundary.add({
      lat: 34.017714,
      lng: -118.499033,
      radius: 50, // in meters
      id: 'Chipotle',
    })
      .then(() => console.log('success!'))
      .catch((e: any) => console.error('error :(', e));

    Boundary.on(Events.ENTER, (id: any) => {
      // Prints 'Get out of my Chipotle!!'
      console.log(`Get out of my ${id}!!`);
    });

    Boundary.on(Events.EXIT, (id: any) => {
      // Prints 'Ya! You better get out of my Chipotle!!'
      console.log(`Ya! You better get out of my ${id}!!`);
    });

    return () => {
      // Remove the events
      Boundary.off(Events.ENTER);
      Boundary.off(Events.EXIT);

      // Remove the boundary from native API´s
      Boundary.remove('Chipotle')
        .then(() => console.log('Goodbye Chipotle :('))
        .catch((e: any) => console.log('Failed to delete Chipotle :)', e));
    };
  }, []);
```

The only weird thing I did was to enable Hermes, could that be the problem?

Thanks,

**Comment by NuclearKev** [comment] 2024-02-08 17:56
> The only weird thing I did was to enable Hermes, could that be the problem?

Hermes is enabled by default on RN >=0.70, I believe. That being said, it would be enabled for me as well. Are you able to `console.log` the value of `Boundary`? I use it a similar way for our app so I'm not sure why it's working for me and not for you!

**Comment by Goye** [comment] 2024-02-08 18:24
You are right so that's pretty weird, I just followed the steps of the new project generation:

```
npx react-native@latest init AwesomeProject
```

Important that I am using:

package | version
-- | --
node | v18.16.1
xcode | 15.2

~~Could it be something related to the Node version, which version are you using?~~ I can't run the project with a minor node version so it could be something related to the Xcode update, which Xcode version are you using? @NuclearKev

**Comment by NuclearKev** [comment] 2024-02-08 18:59
I'm using node 19.6.1. Hm, yes, I'm only on version 14.2 of xcode. I'm running the last version of MacOS as well so I may need to do an OS update to get 15.2

EDIT:
Yes, it requires the next version of MacOS. I'll give it an update over the weekend and see if I can reproduce this bug.

**Comment by NuclearKev** [comment] 2024-02-13 20:21
@Goye Hi there, I've upgrade my computer and got the latest xcode. I _still_ don't get that error and it appears to be working as expected. Maybe I have something cached somewhere that preventing this from happening for me?

**Comment by NuclearKev** [comment] 2024-02-13 20:53
This just in! I was able to reproduce it! With a new project. I'll look into fixing this.

**Comment by NuclearKev** [comment] 2024-02-13 21:03
@Goye I found the problem. It's with the pod. Looks like it's using the older style of pod importing so you'll have to add: 
```
pod 'RNBoundary', :path => '../node_modules/react-native-boundary-sked/ios'
```
in your Podfile until I add in the automatic pod stuff. :)

**Comment by NuclearKev** [comment] 2024-02-13 21:14
Please update `package.json` to use version 1.1.5! It should be fixed :)

**Closed as completed by NuclearKev** 2024-02-13 21:14 UTC

**Comment by Goye** [comment] 2024-02-13 22:48
Hey @NuclearKev,

Yaaay thank you very much, we have decided to go ahead with version 0.67 due to other issues, but thanks again for the fix!
